### PR TITLE
:bug: onLinkClick with the right link

### LINKED ISSUE #32: :bug: onClick Link the wrong link data is sent
**branch:** master

image

### PR DESCRIPTION
**Pull request by fabienjuif**
fixes #32

### CODE REVIEW

File: src/makeCurvedLinks.ts [hunk 1]
```diff
@@ -30,58 +38,73 @@ const scale = ({ source, target }: Link, size: number) => ({
...
 }
 
-export default (links: Link[], { offset, size = 1 }: LinksOptions) => {
+const addSVGPath = (options: LinksOptions) => (groups: Link[]) => {
+  return groups.map((link, index, { length }) =>
+    createCurve(link, index, length, groups.length, options),
+  )
+}
+
+export default (
```
Comment (fabienjuif) [inline src/makeCurvedLinks.ts]: the important things is here
the other modification was to understand the algorithm better
